"""Nsys isolated execution, report recovery and cleanup."""
from __future__ import annotations

import os
from typing import Any, Dict, List, Mapping, Optional

from acprof.host.command import run_command
from acprof.host.detect import TaskInfo
from acprof.host.profiler_support import (
    docker_env,
    execution_thread_environment,
    format_scale_value,
    parse_last_json_line,
    profile_runner_args,
    profiler_container_command,
    relative_artifact,
    safe_filename_token,
)
from acprof.host.profilers.execution_environment import (
    command_detail,
)
from acprof.host.profilers.execution_parsers import (
    NSYS_REPORTS,
    finite_float,
    parse_nsys_stats_reports,
)

NSYS_TOOL = "nsys"


NSYS_FIELDS = (
    "host_inference_wall_time_ms_per_request_nsys",
    "cuda_api_time_sum_ms_per_request_nsys",
    "cuda_api_call_count_per_request_nsys",
    "gpu_kernel_time_sum_ms_per_request_nsys",
    "gpu_kernel_launch_count_per_request_nsys",
    "gpu_memcpy_time_sum_ms_per_request_nsys",
    "gpu_memcpy_count_per_request_nsys",
    "gpu_memcpy_bytes_per_request_nsys",
)


NSYS_NVTX_RANGE = "acprof_compute"


NSYS_TRACE_DOMAINS = "cuda,nvtx"


NSYS_RAW_STREAM_SUFFIX = ".qdstrm"


def error_entry(
    entry: Mapping[str, Any],
    error: str,
    *,
    report: Optional[str] = None,
) -> Dict[str, Any]:
    result: Dict[str, Any] = {
        "input_scale": float(entry["input_scale"]),
        "tool": NSYS_TOOL,
        **{field: None for field in NSYS_FIELDS},
        "compute_profile_error_nsys": error,
        "error": error,
    }
    if report is not None:
        result["report"] = report
    return result


def _nsys_sqlite_path(report_path: str) -> str:
    """Return the SQLite cache path generated by ``nsys stats``."""
    return f"{os.path.splitext(os.fspath(report_path))[0]}.sqlite"


def _discard_nsys_sqlite(report_path: str) -> None:
    """Remove the derived SQLite cache while preserving the raw report."""
    try:
        os.remove(_nsys_sqlite_path(report_path))
    except FileNotFoundError:
        pass


def _run_nsys_stats(nsys_bin: str, report_path: str) -> Dict[str, str]:
    outputs: Dict[str, str] = {}
    sqlite_path = _nsys_sqlite_path(report_path)
    try:
        for index, report_name in enumerate(NSYS_REPORTS):
            refresh_export = ["--force-export=true"] if index == 0 else []
            # Nsys 2026.1 can report a freshly exported SQLite cache as older
            # than its .nsys-rep when both files were written in the same
            # second.  Export once from the raw report, then pass the SQLite
            # file directly so later reports do not repeat that freshness
            # check.
            stats_input = report_path if index == 0 else sqlite_path
            result = run_command(
                [
                    nsys_bin,
                    "stats",
                    "--report",
                    report_name,
                    "--format",
                    "csv",
                    "--timeunit",
                    "nsec",
                    "--output",
                    "-",
                    *refresh_export,
                    stats_input,
                ],
                check=False,
            )
            if result.returncode != 0:
                raise RuntimeError(
                    f"nsys_stats_failed:{report_name}:"
                    f"{command_detail(result)}"
                )
            stdout = str(result.stdout or "")
            stderr = str(result.stderr or "")
            outputs[report_name] = "\n".join(
                part for part in (stdout, stderr) if part.strip()
            )
        return outputs
    finally:
        _discard_nsys_sqlite(report_path)


def _discard_nsys_raw_stream(path: str) -> int:
    """Remove an intermediate QDSTRM and return its former byte size."""
    try:
        size = os.path.getsize(path)
    except OSError:
        size = 0
    try:
        os.remove(path)
    except FileNotFoundError:
        pass
    return size


def _collect_nsys_entry(
    *,
    task_info: TaskInfo,
    image_tag: str,
    nsys_bin: str,
    nsys_mount_root: str,
    cpu: int,
    mem: int,
    payload_file: str,
    profile_root: str,
    output_dir: str,
    entry: Mapping[str, Any],
    repeat: int,
) -> Dict[str, Any]:
    scale_label = safe_filename_token(
        format_scale_value(float(entry["input_scale"]))
    )
    stem = f"nsys_cpu_{cpu}_mem_{mem}_scale_{scale_label}"
    filename = f"{stem}.nsys-rep"
    host_report = os.path.join(profile_root, filename)
    host_raw_stream = os.path.join(
        profile_root,
        f"{stem}{NSYS_RAW_STREAM_SUFFIX}",
    )
    relative_report = relative_artifact(host_report, output_dir)
    # A failed importer may have left a huge stream from an earlier attempt.
    _discard_nsys_raw_stream(host_raw_stream)
    base_cmd = profiler_container_command(
        task_info=task_info,
        image_tag=image_tag,
        cpu=cpu,
        mem=mem,
        use_gpu=True,
        payload_file=payload_file,
        profile_root=profile_root,
        tool_mount_roots=(nsys_mount_root,),
    )
    base_cmd = execution_thread_environment(base_cmd)
    base_cmd = docker_env(
        base_cmd,
        "NSYS_NVTX_PROFILER_REGISTER_ONLY",
        "0",
    )
    command = [
        *base_cmd,
        nsys_bin,
        "profile",
        f"--trace={NSYS_TRACE_DOMAINS}",
        "--capture-range=nvtx",
        f"--nvtx-capture={NSYS_NVTX_RANGE}",
        "--capture-range-end=stop",
        "--sample=none",
        "--cpuctxsw=none",
        "--force-overwrite=true",
        f"--output=/profiles/{stem}",
        *profile_runner_args(dict(entry), repeat, "gpu"),
    ]
    try:
        result = run_command(command, check=False)
    except Exception:
        _discard_nsys_raw_stream(host_raw_stream)
        raise
    if result.returncode != 0:
        discarded_bytes = _discard_nsys_raw_stream(host_raw_stream)
        discarded = (
            f":discarded_qdstrm_bytes={discarded_bytes}"
            if discarded_bytes
            else ""
        )
        return error_entry(
            entry,
            f"nsys_failed:{command_detail(result)}{discarded}",
            report=relative_report if os.path.isfile(host_report) else None,
        )
    if not os.path.isfile(host_report):
        discarded_bytes = _discard_nsys_raw_stream(host_raw_stream)
        discarded = (
            f":discarded_qdstrm_bytes={discarded_bytes}"
            if discarded_bytes
            else ""
        )
        return error_entry(
            entry,
            f"nsys_import_failed:report_not_found{discarded}",
        )
    _discard_nsys_raw_stream(host_raw_stream)

    runner_payload = parse_last_json_line(str(result.stdout or ""))
    wall_time = finite_float(
        runner_payload.get("profile_window_wall_time_ms_per_request")
    )
    if wall_time is None:
        total_wall_time = finite_float(
            runner_payload.get("profile_window_wall_time_ms")
        )
        if total_wall_time is not None:
            wall_time = total_wall_time / max(1, int(repeat))
    if wall_time is None or wall_time < 0:
        return error_entry(
            entry,
            "nsys_parse_failed:profile_window_wall_time_missing",
            report=relative_report,
        )

    try:
        stats = parse_nsys_stats_reports(
            _run_nsys_stats(nsys_bin, host_report),
            repeat=repeat,
        )
    except Exception as exc:
        detail = str(exc)
        error = (
            detail
            if detail.startswith(("nsys_parse_failed:", "nsys_stats_failed:"))
            else f"nsys_parse_failed:{detail}"
        )
        return error_entry(
            entry,
            error,
            report=relative_report,
        )

    return {
        "input_scale": float(entry["input_scale"]),
        "tool": NSYS_TOOL,
        "host_inference_wall_time_ms_per_request_nsys": wall_time,
        **stats,
        "compute_profile_error_nsys": "",
        "error": "",
        "report": relative_report,
    }


def profile(
    *,
    entries: List[Dict[str, Any]],
    global_error: str,
    task_info: TaskInfo,
    image_tag: str,
    nsys_bin: Optional[str],
    nsys_mount_root: Optional[str],
    cpu: int,
    mem: int,
    payload_file: str,
    profile_root: str,
    output_dir: str,
    repeat: int,
) -> Dict[str, Any]:
    if global_error or not nsys_bin or not nsys_mount_root:
        error = global_error or "nsys_not_found"
        profiled_entries = [
            error_entry(entry, error)
            for entry in entries
        ]
    else:
        profiled_entries = []
        for entry in entries:
            try:
                profiled_entries.append(
                    _collect_nsys_entry(
                        task_info=task_info,
                        image_tag=image_tag,
                        nsys_bin=nsys_bin,
                        nsys_mount_root=nsys_mount_root,
                        cpu=cpu,
                        mem=mem,
                        payload_file=payload_file,
                        profile_root=profile_root,
                        output_dir=output_dir,
                        entry=entry,
                        repeat=repeat,
                    )
                )
            except Exception as exc:
                profiled_entries.append(
                    error_entry(
                        entry,
                        f"nsys_failed:{exc!r}",
                    )
                )
    return {
        "tool": NSYS_TOOL,
        "repeat": repeat,
        "error": global_error,
        "entries": profiled_entries,
    }
