"""基于同目录临时文件发布产物；调用方负责在测量窗口之外写入。"""
from __future__ import annotations

import json
import math
import os
import stat
import tempfile
from pathlib import Path
from typing import Any, Callable, TextIO, cast

MAX_JSON_ARTIFACT_BYTES = 4 * 1024 * 1024


def _finite_json_number(raw: str) -> float:
    value = float(raw)
    if not math.isfinite(value):
        raise ValueError("non-finite number")
    return value


def read_json_object(path: str | Path, *, label: str = "artifact") -> dict:
    """Read one bounded, finite JSON object without altering the source artifact."""
    source = Path(path)
    with source.open("rb") as stream:
        content = stream.read(MAX_JSON_ARTIFACT_BYTES + 1)
    if len(content) > MAX_JSON_ARTIFACT_BYTES:
        raise ValueError(f"{source}: {label} exceeds the 4 MiB read limit")
    try:
        payload = json.loads(
            content.decode("utf-8"),
            parse_float=_finite_json_number,
            parse_constant=_finite_json_number,
        )
    except (UnicodeError, ValueError, RecursionError) as exc:
        raise ValueError(f"{source}: invalid {label} JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{source}: top-level JSON value must be an object")
    return payload


def require_schema_version(payload: Any, expected: int, artifact: str) -> None:
    """在消费产物前拒绝缺失、过期或未知的协议版本。"""
    version = payload.get("schema_version") if isinstance(payload, dict) else None
    if type(version) is not int or version != expected:
        raise ValueError(
            f"{artifact}: unsupported schema_version={version!r}; expected {expected}. "
            "Use artifacts generated by the current AC-Prof version."
        )


def read_input_scale_plan(path: str | Path) -> dict:
    """Read the current bounded input plan before any runtime or measurement starts."""
    payload = read_json_object(path, label="input scale plan")
    require_schema_version(payload, 2, "input_scale_plan.json")
    return payload


def read_static_metadata(result_dir: str | Path, *, required: bool = False) -> dict:
    """读取当前静态元数据；旧 CSV 和内嵌采集历史均不能自动转换。"""
    from acprof.config import STATIC_META_SCHEMA_VERSION
    directory = Path(result_dir)
    from acprof.artifact_layout import ArtifactLayout
    path = ArtifactLayout.discover(directory).path("static_meta.json")
    if not path.is_file():
        if (directory / "static_meta.csv").exists():
            raise ValueError("static_meta.csv is no longer supported; regenerate current result artifacts")
        if required:
            raise FileNotFoundError(path)
        return {}
    payload = read_json_object(path, label="static metadata")
    require_schema_version(payload, STATIC_META_SCHEMA_VERSION, str(path))
    history = [key for key in payload if key.endswith(("_history", "_last_run"))]
    if history:
        raise ValueError(f"{path}: collection history must be in collection_history.json: {history}")
    from acprof.platform import recorded_identity
    return {**payload, **recorded_identity(payload)}


def _sync_directory(directory: Path) -> None:
    if os.name != "posix":
        return
    directory_fd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def replace_file_durably(source: str | Path, destination: str | Path) -> None:
    """Publish an already-written sibling file and make the rename durable on POSIX."""
    source_path = Path(source)
    destination_path = Path(destination)
    with source_path.open("rb") as stream:
        os.fsync(stream.fileno())
    os.replace(source_path, destination_path)
    _sync_directory(destination_path.parent)


def atomic_write(
    path: str | Path,
    write: Callable[[TextIO], None],
    *,
    default_mode: int = 0o644,
) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(destination.stat().st_mode) if destination.exists() else default_mode
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="",
                                         dir=destination.parent, prefix=f".{destination.name}.",
                                         suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            # NamedTemporaryFile delegates the complete text stream interface.
            write(cast(TextIO, stream))
            stream.flush()
            os.fchmod(stream.fileno(), mode)
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
        temporary = None
        _sync_directory(destination.parent)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def atomic_write_json(path: str | Path, payload: Any) -> None:
    def write(stream: TextIO) -> None:
        json.dump(payload, stream, ensure_ascii=False, indent=2, allow_nan=False)
        stream.write("\n")
    atomic_write(path, write)
