# Metadata only: model weights live exclusively in the host Model Store.
ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}
ARG MODEL_ID
ARG MODEL_REVISION
ARG TASK_FAMILY
ARG RUNTIME_BACKEND
ARG MODEL_ADAPTER=family-default
ARG MODEL_DOWNLOAD_POLICY=auto
ARG MODEL_FILES_KEY
ARG MODEL_DEPENDENCIES_B64=
ENV MODEL_ID=${MODEL_ID} MODEL_REVISION=${MODEL_REVISION}
ENV TASK_FAMILY=${TASK_FAMILY} RUNTIME_BACKEND=${RUNTIME_BACKEND} MODEL_ADAPTER=${MODEL_ADAPTER}
ENV MODEL_DOWNLOAD_POLICY=${MODEL_DOWNLOAD_POLICY}
ENV ACPROF_MODEL_DEPENDENCIES_B64=${MODEL_DEPENDENCIES_B64}
ENV HF_HUB_CACHE=/models/hf
LABEL org.acprof.model-files-key=${MODEL_FILES_KEY} org.acprof.image-kind="model-plan"
ENV HF_HUB_DISABLE_XET=1
COPY model-store.json /models/model-store.json
