# Metadata only: model weights live exclusively in the host Model Store.
ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}
ARG MODEL_ID
ARG MODEL_REVISION
ARG HF_ENDPOINT=https://hf-mirror.com
ARG HF_DOWNLOAD_MODE=mirror-only
ARG ACPROF_ALLOW_PROXY_FALLBACK=0
ARG HF_FALLBACK_ENDPOINTS=
ARG TASK_FAMILY
ARG RUNTIME_BACKEND
ARG MODEL_ADAPTER=family-default
ARG MODEL_DOWNLOAD_POLICY=auto
ARG MODEL_FILES_KEY
ARG MODEL_DEPENDENCIES_B64=
ENV MODEL_ID=${MODEL_ID} MODEL_REVISION=${MODEL_REVISION} HF_ENDPOINT=${HF_ENDPOINT}
ENV TASK_FAMILY=${TASK_FAMILY} RUNTIME_BACKEND=${RUNTIME_BACKEND} MODEL_ADAPTER=${MODEL_ADAPTER}
ENV MODEL_DOWNLOAD_POLICY=${MODEL_DOWNLOAD_POLICY}
ENV ACPROF_MODEL_DEPENDENCIES_B64=${MODEL_DEPENDENCIES_B64}
ENV HF_HUB_CACHE=/models/hf
LABEL org.acprof.model-files-key=${MODEL_FILES_KEY} org.acprof.image-kind="model-plan"
ENV HF_FALLBACK_ENDPOINTS=${HF_FALLBACK_ENDPOINTS}
ENV HF_DOWNLOAD_MODE=${HF_DOWNLOAD_MODE} HF_HUB_DISABLE_XET=1 ACPROF_ALLOW_PROXY_FALLBACK=${ACPROF_ALLOW_PROXY_FALLBACK}
COPY model-store.json /models/model-store.json
